/* eslint-disable import/prefer-default-export */

import { categories as categoriesIcon } from '../../images';

export const projects = [{
  title: '傳說中的廚具永靈刀',
  image: 'https://i2.kknews.cc/SIG=24ao12m/3p6o00027520sp12po55.jpg',
  author: '許林',
  likes: 999,
}, {
  title: '傳說中的廚具永靈刀',
  image: 'https://i2.kknews.cc/SIG=24ao12m/3p6o00027520sp12po55.jpg',
  author: '許林',
  likes: 999,
}, {
  title: '傳說中的廚具永靈刀',
  image: 'https://i2.kknews.cc/SIG=24ao12m/3p6o00027520sp12po55.jpg',
  author: '許林',
  likes: 999,
}, {
  title: '傳說中的廚具永靈刀',
  image: 'https://i2.kknews.cc/SIG=24ao12m/3p6o00027520sp12po55.jpg',
  author: '許林',
  likes: 999,
}, {
  title: '傳說中的廚具永靈刀',
  image: 'https://i2.kknews.cc/SIG=24ao12m/3p6o00027520sp12po55.jpg',
  author: '許林',
  likes: 999,
}, {
  title: '傳說中的廚具永靈刀',
  image: 'https://i2.kknews.cc/SIG=24ao12m/3p6o00027520sp12po55.jpg',
  author: '許林',
  likes: 999,
}, {
  title: '傳說中的廚具永靈刀',
  image: 'https://i2.kknews.cc/SIG=24ao12m/3p6o00027520sp12po55.jpg',
  author: '許林',
  likes: 999,
}, {
  title: '傳說中的廚具永靈刀',
  image: 'https://i2.kknews.cc/SIG=24ao12m/3p6o00027520sp12po55.jpg',
  author: '許林',
  likes: 999,
}, {
  title: '傳說中的廚具永靈刀',
  image: 'https://i2.kknews.cc/SIG=24ao12m/3p6o00027520sp12po55.jpg',
  author: '許林',
  likes: 999,
}, {
  title: '傳說中的廚具永靈刀',
  image: 'https://i2.kknews.cc/SIG=24ao12m/3p6o00027520sp12po55.jpg',
  author: '許林',
  likes: 999,
}];

export const categories = [{
  name: '木工',
  image: categoriesIcon.WOODWORK,
}, {
  name: '電子',
  image: categoriesIcon.ELECTRONIC,
}, {
  name: '電腦',
  image: categoriesIcon.COMPUTER,
}, {
  name: '摺紙',
  image: categoriesIcon.PAPERWORK,
}, {
  name: '美髮',
  image: categoriesIcon.HAIR,
}, {
  name: '木雕',
  image: categoriesIcon.WOODCURVING,
}, {
  name: '木工',
  image: categoriesIcon.WOODWORK,
}, {
  name: '電子',
  image: categoriesIcon.ELECTRONIC,
}, {
  name: '電腦',
  image: categoriesIcon.COMPUTER,
}, {
  name: '摺紙',
  image: categoriesIcon.PAPERWORK,
}, {
  name: '美髮',
  image: categoriesIcon.HAIR,
}, {
  name: '木雕',
  image: categoriesIcon.WOODCURVING,
}, {
  name: '木工',
  image: categoriesIcon.WOODWORK,
}, {
  name: '電子',
  image: categoriesIcon.ELECTRONIC,
}, {
  name: '電腦',
  image: categoriesIcon.COMPUTER,
}, {
  name: '摺紙',
  image: categoriesIcon.PAPERWORK,
}, {
  name: '美髮',
  image: categoriesIcon.HAIR,
}, {
  name: '木雕',
  image: categoriesIcon.WOODCURVING,
}, {
  name: '木工',
  image: categoriesIcon.WOODWORK,
}, {
  name: '電子',
  image: categoriesIcon.ELECTRONIC,
}, {
  name: '電腦',
  image: categoriesIcon.COMPUTER,
}, {
  name: '摺紙',
  image: categoriesIcon.PAPERWORK,
}, {
  name: '美髮',
  image: categoriesIcon.HAIR,
}, {
  name: '木雕',
  image: categoriesIcon.WOODCURVING,
}];
