export default {
  headerHeight: 80,
  bottomTabBarHeight: 50,
  topTabBarHeight: 47,
  homeSectionPadding: 20,
  searchBarHeight: 35,
  postProfileImageSize: 50,
  projectProfileImageSize: 50,
  profileImageSize: 70,
  profileSettingImageSize: 120,
  userProjectListImageSize: 100,
  followPostImageSize: 200,
  followPostAuthorInfoHeight: 50,
  followPostAuthorImageSize: 30,
  settingItemHeight: 60,
  refreshAnimationHeight: 60,
  projectSectionBorderRadius: 5,
  horCardBorderRadius: 5,
};
