/* eslint-disable import/prefer-default-export */

import { categories as categoriesIcon } from '../../images';

export const categories = [{
  name: '木工',
  image: categoriesIcon.WOODWORK,
}, {
  name: '電子',
  image: categoriesIcon.ELECTRONIC,
}, {
  name: '電腦',
  image: categoriesIcon.COMPUTER,
}, {
  name: '摺紙',
  image: categoriesIcon.PAPERWORK,
}, {
  name: '美髮',
  image: categoriesIcon.HAIR,
}, {
  name: '木雕',
  image: categoriesIcon.WOODCURVING,
}, {
  name: '木工',
  image: categoriesIcon.WOODWORK,
}, {
  name: '電子',
  image: categoriesIcon.ELECTRONIC,
}, {
  name: '電腦',
  image: categoriesIcon.COMPUTER,
}, {
  name: '摺紙',
  image: categoriesIcon.PAPERWORK,
}, {
  name: '美髮',
  image: categoriesIcon.HAIR,
}, {
  name: '木雕',
  image: categoriesIcon.WOODCURVING,
}, {
  name: '木工',
  image: categoriesIcon.WOODWORK,
}, {
  name: '電子',
  image: categoriesIcon.ELECTRONIC,
}, {
  name: '電腦',
  image: categoriesIcon.COMPUTER,
}, {
  name: '摺紙',
  image: categoriesIcon.PAPERWORK,
}, {
  name: '美髮',
  image: categoriesIcon.HAIR,
}, {
  name: '木雕',
  image: categoriesIcon.WOODCURVING,
}, {
  name: '木工',
  image: categoriesIcon.WOODWORK,
}, {
  name: '電子',
  image: categoriesIcon.ELECTRONIC,
}, {
  name: '電腦',
  image: categoriesIcon.COMPUTER,
}, {
  name: '摺紙',
  image: categoriesIcon.PAPERWORK,
}, {
  name: '美髮',
  image: categoriesIcon.HAIR,
}, {
  name: '木雕',
  image: categoriesIcon.WOODCURVING,
}];
